### PR TITLE
Assignment Completed With Server Hosted In Railway

### PR DESCRIPTION
**Pull request by amaljohn2304**
Hey there I am Amal John (https://wellfound.com/u/amal-john-5). I have completed the task and hosted it in Railway. Please verify whenever you find yourself free.

Regards,
    Amal

### CODE REVIEW

**Comment by amanintech** [comment]
Kindly Share the link to railway deployment with the fast API endpoint

**Comment by amaljohn2304** [comment]
The endpoint for the project is :
https://dinnerfy-ds-production.up.railway.app/recipe
and the request body is:
{
    "RecipeID": 60,
    "Servings": 3
}

**Comment by amaljohn2304** [comment]
> Kindly Share the link to railway deployment with the fast API endpoint

I have provided the necessary details in the previous comment. I just Reopened for visibility.

**Comment by amanintech** [comment]
Congratulation, you have passed the assignment

**Pull request merged**
